// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/product_srv.proto

package product_srv

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Productsrv service

func NewProductsrvEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Productsrv service

type ProductsrvService interface {
	Call(ctx context.Context, in *CallRequest, opts ...client.CallOption) (*CallResponse, error)
	ClientStream(ctx context.Context, opts ...client.CallOption) (Productsrv_ClientStreamService, error)
	ServerStream(ctx context.Context, in *ServerStreamRequest, opts ...client.CallOption) (Productsrv_ServerStreamService, error)
	BidiStream(ctx context.Context, opts ...client.CallOption) (Productsrv_BidiStreamService, error)
}

type productsrvService struct {
	c    client.Client
	name string
}

func NewProductsrvService(name string, c client.Client) ProductsrvService {
	return &productsrvService{
		c:    c,
		name: name,
	}
}

func (c *productsrvService) Call(ctx context.Context, in *CallRequest, opts ...client.CallOption) (*CallResponse, error) {
	req := c.c.NewRequest(c.name, "Productsrv.Call", in)
	out := new(CallResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productsrvService) ClientStream(ctx context.Context, opts ...client.CallOption) (Productsrv_ClientStreamService, error) {
	req := c.c.NewRequest(c.name, "Productsrv.ClientStream", &ClientStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &productsrvServiceClientStream{stream}, nil
}

type Productsrv_ClientStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	CloseSend() error
	Close() error
	Send(*ClientStreamRequest) error
}

type productsrvServiceClientStream struct {
	stream client.Stream
}

func (x *productsrvServiceClientStream) CloseSend() error {
	return x.stream.CloseSend()
}

func (x *productsrvServiceClientStream) Close() error {
	return x.stream.Close()
}

func (x *productsrvServiceClientStream) Context() context.Context {
	return x.stream.Context()
}

func (x *productsrvServiceClientStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *productsrvServiceClientStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *productsrvServiceClientStream) Send(m *ClientStreamRequest) error {
	return x.stream.Send(m)
}

func (c *productsrvService) ServerStream(ctx context.Context, in *ServerStreamRequest, opts ...client.CallOption) (Productsrv_ServerStreamService, error) {
	req := c.c.NewRequest(c.name, "Productsrv.ServerStream", &ServerStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &productsrvServiceServerStream{stream}, nil
}

type Productsrv_ServerStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	CloseSend() error
	Close() error
	Recv() (*ServerStreamResponse, error)
}

type productsrvServiceServerStream struct {
	stream client.Stream
}

func (x *productsrvServiceServerStream) CloseSend() error {
	return x.stream.CloseSend()
}

func (x *productsrvServiceServerStream) Close() error {
	return x.stream.Close()
}

func (x *productsrvServiceServerStream) Context() context.Context {
	return x.stream.Context()
}

func (x *productsrvServiceServerStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *productsrvServiceServerStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *productsrvServiceServerStream) Recv() (*ServerStreamResponse, error) {
	m := new(ServerStreamResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *productsrvService) BidiStream(ctx context.Context, opts ...client.CallOption) (Productsrv_BidiStreamService, error) {
	req := c.c.NewRequest(c.name, "Productsrv.BidiStream", &BidiStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &productsrvServiceBidiStream{stream}, nil
}

type Productsrv_BidiStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	CloseSend() error
	Close() error
	Send(*BidiStreamRequest) error
	Recv() (*BidiStreamResponse, error)
}

type productsrvServiceBidiStream struct {
	stream client.Stream
}

func (x *productsrvServiceBidiStream) CloseSend() error {
	return x.stream.CloseSend()
}

func (x *productsrvServiceBidiStream) Close() error {
	return x.stream.Close()
}

func (x *productsrvServiceBidiStream) Context() context.Context {
	return x.stream.Context()
}

func (x *productsrvServiceBidiStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *productsrvServiceBidiStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *productsrvServiceBidiStream) Send(m *BidiStreamRequest) error {
	return x.stream.Send(m)
}

func (x *productsrvServiceBidiStream) Recv() (*BidiStreamResponse, error) {
	m := new(BidiStreamResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Productsrv service

type ProductsrvHandler interface {
	Call(context.Context, *CallRequest, *CallResponse) error
	ClientStream(context.Context, Productsrv_ClientStreamStream) error
	ServerStream(context.Context, *ServerStreamRequest, Productsrv_ServerStreamStream) error
	BidiStream(context.Context, Productsrv_BidiStreamStream) error
}

func RegisterProductsrvHandler(s server.Server, hdlr ProductsrvHandler, opts ...server.HandlerOption) error {
	type productsrv interface {
		Call(ctx context.Context, in *CallRequest, out *CallResponse) error
		ClientStream(ctx context.Context, stream server.Stream) error
		ServerStream(ctx context.Context, stream server.Stream) error
		BidiStream(ctx context.Context, stream server.Stream) error
	}
	type Productsrv struct {
		productsrv
	}
	h := &productsrvHandler{hdlr}
	return s.Handle(s.NewHandler(&Productsrv{h}, opts...))
}

type productsrvHandler struct {
	ProductsrvHandler
}

func (h *productsrvHandler) Call(ctx context.Context, in *CallRequest, out *CallResponse) error {
	return h.ProductsrvHandler.Call(ctx, in, out)
}

func (h *productsrvHandler) ClientStream(ctx context.Context, stream server.Stream) error {
	return h.ProductsrvHandler.ClientStream(ctx, &productsrvClientStreamStream{stream})
}

type Productsrv_ClientStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*ClientStreamRequest, error)
}

type productsrvClientStreamStream struct {
	stream server.Stream
}

func (x *productsrvClientStreamStream) Close() error {
	return x.stream.Close()
}

func (x *productsrvClientStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *productsrvClientStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *productsrvClientStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *productsrvClientStreamStream) Recv() (*ClientStreamRequest, error) {
	m := new(ClientStreamRequest)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (h *productsrvHandler) ServerStream(ctx context.Context, stream server.Stream) error {
	m := new(ServerStreamRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.ProductsrvHandler.ServerStream(ctx, m, &productsrvServerStreamStream{stream})
}

type Productsrv_ServerStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*ServerStreamResponse) error
}

type productsrvServerStreamStream struct {
	stream server.Stream
}

func (x *productsrvServerStreamStream) Close() error {
	return x.stream.Close()
}

func (x *productsrvServerStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *productsrvServerStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *productsrvServerStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *productsrvServerStreamStream) Send(m *ServerStreamResponse) error {
	return x.stream.Send(m)
}

func (h *productsrvHandler) BidiStream(ctx context.Context, stream server.Stream) error {
	return h.ProductsrvHandler.BidiStream(ctx, &productsrvBidiStreamStream{stream})
}

type Productsrv_BidiStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*BidiStreamResponse) error
	Recv() (*BidiStreamRequest, error)
}

type productsrvBidiStreamStream struct {
	stream server.Stream
}

func (x *productsrvBidiStreamStream) Close() error {
	return x.stream.Close()
}

func (x *productsrvBidiStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *productsrvBidiStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *productsrvBidiStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *productsrvBidiStreamStream) Send(m *BidiStreamResponse) error {
	return x.stream.Send(m)
}

func (x *productsrvBidiStreamStream) Recv() (*BidiStreamRequest, error) {
	m := new(BidiStreamRequest)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
